services:
  - type: worker  # Меняем с web на worker!
    name: radio-mir-monitor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python monitor.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GITHUB_TOKEN
        sync: false
    plan: free
